name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ main ] 
    paths:
      - 'yii2-devops-stack/sample-php-yii2-app/**'
      - 'Dockerfile'
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Hash commit and TimeStamp for Image Version
        run: |
          export LATEST_COMMIT_HASH=$(git log -n 1 --format=%H | cut -c 1-8)
          echo $LATEST_COMMIT_HASH
          export TIMESTAMP=$(git log --pretty=format:%cd -n 1 --date=iso | sed "s/[- :]//g" | sed "s/+.*$//")
          echo $TIMESTAMP
          echo "TAG_VERSION=$LATEST_COMMIT_HASH-$TIMESTAMP" >> $GITHUB_ENV

 
     - name: Build and push Docker image
       run: |
         docker build -t {{ secrets.DOCKERHUB_USERNAME }}/yii2-app:{{ env.TAG_VERSION }} .
         docker push {{ secrets.DOCKERHUB_USERNAME }}/yii2-app:{{ env.TAG_VERSION }}
