name: Build and Push Docker Image to ECR

on:
  push:
    branches: [ main ] 
    paths:
      - 'yii2-devops-stack/sample-php-yii2-app/**'
      - 'Dockerfile'
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Hash commit and TimeStamp for Image Version
        run: |
          export LATEST_COMMIT_HASH=$(git log -n 1 --format=%H | cut -c 1-8)
          echo $LATEST_COMMIT_HASH
          export TIMESTAMP=$(git log --pretty=format:%cd -n 1 --date=iso | sed "s/[- :]//g" | sed "s/+.*$//")
          echo $TIMESTAMP
          echo "TAG_VERSION=$LATEST_COMMIT_HASH-$TIMESTAMP" >> $GITHUB_ENV

 
      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:$TAG_VERSION
          docker build -t $IMAGE .
          docker push $IMAGE
          
          
      - name: SSH into EC2 and update service
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:${{ env.TAG_VERSION }}
            docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/yii2-app:{{ env.TAG_VERSION }}  yii2app
            


